### ISSUE TITLE
Checkpoint files for Conceptual Captioning

### ISSUE THREAD

**Issue by sgondala** [ruotianluo/GoogleConceptualCaptioning#3]
Are there pretrained weights for conceptual captions trained on the topdown model?

In the googletalk.json file you provided, the vocabulary is of the size 16,303. However, the first embedding layer in the topdown/model-best.json is of size 9488 (https://drive.google.com/drive/folders/0B7fNdx_jAqhtT3pBQlR6emJXM1U). It seems like the pretrained weights provided are for coco but not for google conceptual captions.

**Comment by ruotianluo** [comment]
https://drive.google.com/open?id=18bRlDMt589kC5e6dtY-LQJovPYjlNHqV

**Comment by sgondala** [comment]
Thanks for quick response. 

I couldn't exactly make from the name which one is topdown model. I looked at infos and found trans_* are transformer models and best_smoothing is att2in. Is there a topdown based model?

**Comment by ruotianluo** [comment]
there is no topdown model.

**Comment by irolaina** [comment]
Hi! Are all models trained on google conceptual captions (gcc) using bottom-up features? Is it possible to evaluate on own images using the gcc models? Evaluation on own images seems to require resnet101, though to my understanding gcc models are trained with bottom-up features. Could you please clarify this? Thanks!

**Comment by ruotianluo** [comment]
Look at docker image ruotianluo/conceptual_ens3.
It has the ability to run on new images.

And, ignore the evaluating on your own images in this repo.
