### ISSUE TITLE
Bounding boxes file for Conceptual Captions

### ISSUE THREAD

**Issue by achiyaj** [ruotianluo/GoogleConceptualCaptioning#4]
Hi,

Is there a file containing the detected bounding boxes for the Conceptual Captions bottom-up features?
By looking at the code it seems like this file should be called googlebu_box.lmdb, but I don't see such file in the drive.

Thanks!

**Comment by ruotianluo** [comment]
I didn't use it.

**Comment by ruotianluo** [comment]
In fact I don't have it.

**Comment by achiyaj** [comment]
I see. Thanks for your quick reply!
